### ISSUE TITLE
Code check permission error on Windows

### ISSUE THREAD

**Issue by carlosperate** [ntoll/mu#117]
When pressing the check button:

```
Traceback (most recent call last):
  File "C:\workspace\mu_\mu\logic.py", line 532, in check_code
    pep8 = check_pycodestyle(tab.text())
  File "C:\workspace\mu_\mu\logic.py", line 123, in check_pycodestyle
    os.remove(code_filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\IEUser\\AppData\\Local\\Temp\\tmpdeeh1sux'

```

Using the resource monitor, it indicates the file is locked by the python process.

Tested on Win10x64 (the built .exe file, fails silently) and Win7x32 (using python 3.4.4 32bit, with the above trace).

**Comment by carlosperate** [comment]
Weirdly enough while looking into this, pyflakes freaked out and started crashing on launch, as in the entire python process would crash as soon as the `run.py` file was executed. Went away by pip uninstall and install pyflakes.
Leaving this here in case it happens to somebody else.

**Comment by carlosperate** [comment]
Just to clarify, this issue does not cause the application to crash, it just causes the check button to "not do anything".
